name: cclmoff-env
channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.10
- pip
- pip:
  - torch==2.0.1
  - torchvision==0.15.2
  - torchaudio==2.0.1
  - numpy==1.23.5
  - scipy==1.9.3
  - pandas==1.5.2
  - matplotlib==3.6.2
  - seaborn==0.12.1
  - tqdm==4.64.1
  - scikit-learn==1.1.3
